name: CI - Ubuntu OS

on:
  push:
    branches: [ main, lab, redesign-parsing-system ]
  pull_request:
    branches: [ main, lab ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: mkdir sample/lib; make CI-TEST-Wopslang;
  Fizzbuzz:
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: mkdir sample/lib; make CI-TEST-Wopslang; mv Wopslang sample/;
    - name: run
      run: cd sample; ./Wopslang fizzbuzz.wops debug > out;
  Hailstone_Sequence:
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: mkdir sample/lib; make CI-TEST-Wopslang; mv Wopslang sample/;
    - name: run
      run: cd sample; tree; ./Wopslang hailstone_sequence.wops debug > out;
  Hello_Wopslang:
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: mkdir sample/lib; make CI-TEST-Wopslang; mv Wopslang sample/;
    - name: run
      run: cd sample; tree; ./Wopslang hello_wopslang.wops debug > out;
  
    
