name: CI - Windows OS

on:
  push:
    branches: [ main, lab ]
  pull_request:
    branches: [ main, lab ]

jobs:
  Build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: mkdir sample/lib; make CI-TEST-Wopslang;
  Fizzbuzz:
    needs: Build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: mkdir sample/lib; make CI-TEST-Wopslang; mv Wopslang.exe sample/;
    - name: run
      run: cd sample; ./Wopslang.exe fizzbuzz.wops debug; # for test
  Hailstone_Sequence:
    needs: Build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: mkdir sample/lib; make CI-TEST-Wopslang; mv Wopslang.exe sample/;
    - name: run
      run: cd sample; tree; ./Wopslang.exe hailstone_sequence.wops debug > out;
  Hello_Wopslang:
    needs: Build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: mkdir sample/lib; make CI-TEST-Wopslang; mv Wopslang.exe sample/;
    - name: run
      run: cd sample; tree; ./Wopslang.exe hello_wopslang.wops debug > out;
  
    
